travis:
  secure:
    BINSTAR_TOKEN: Ovt4SnJ9Om0MiqNAfqgUAMtVy/04aCgYHjGMwNkbf00PhRMmM7FsrRXit0zSKSCdlH2UnvgKTBx9PbkWwHcrGiqiIJGkCL19oQSvEmbWpXa4Q5rKUBA79YjAnJlTJklmQsyFyxURRUjHdpgf5rD+O7QGE2Zw3tHTpVhACKWDvUf/IL6fIebyenwrFgIIzXhqn4HJMAMUbQVh0nBR4nsk7QNQVjm8UtHrNoyVCj7/RyRzTG1gATtwp/frTkKjJ69S0nOU1Ydh+yX6yznkppjC+tJ8iyeXivCSsDtn5jpEu094a+SPbQrhuNZXNg3EpjPAdgJxVOW88vXifOxar3/8vs1u6LLTi1e7yLLjH+KfR5/YsijWcJCjT9oCxHUj5dmfdABtrLRC3bWdIZVEc8eGpDoHmX8OuYETgL90EGPRymchHAcC4dyYtG8+wtJ/irXgjpmHAa6dGqbPuZ+kIXycQv7IVCZm6JIUT0QWmsqOkM7/Zzy4SBT1SMis0TRGpJNsUGX2wIcByp0i/ij8LhwyjVddJjDCp3iIPDrD6qe1i2MsivEzlhPiPST95OCzzWHl86hPUR4hh/mmMaj+O8lyfTIcqr205dUeMSci7GIPdsIEM0pO5kTF/G/SNlQMUGiWoaJaVJ0XuCkFei3Q9uGKrWObrRFbYP2P8LPtEwf7vu4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
